creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          # admin
          - age18z6wevr8ze5azvq7nfty3l29s7887l8n5mefr64avhlthtr4uvnqw90nfs
          # laptop
          - age1aee7tp00ae7vngf50jn2zd9h2ddmcyaenkv4w3vlgec5frmvrc8qg64423
          # template
          - age1v9tajgxsj7zkauwf6p50qk3ngtlqspqr89cl83a6cfkd20835etq4frnmj
          # racknerd-vps
          - age1qsst00d5j0t57ajzclj58kmxhfmtng58r3dez8rtu47nqmcjg4pqt9204k
