{ pkgs, config, ... }: {
  environment.systemPackages = with pkgs; [
    git curl zsh fzf nettools sops age
  ];

  sops.age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];

  sops.secrets."github_pat" = {
    sopsFile = ../secrets/laptop.yaml;
  };

  services.openssh.enable = true;
  programs.zsh.enable = true;
  users.defaultUserShell = pkgs.zsh;

  users.users.mafyuh = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    openssh.authorizedKeys.keys = [ "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC2I9wGjs+G/RO5aJJDNL0j5yPExvX7RETQIO6OmXbvx Generated By Termius" ];
  };
  security.sudo.wheelNeedsPassword = false;

  services.comin = {
    enable = true;
    remotes = [{
      name = "origin";
      url = "https://github.com/Mafyuh/nixos.git";
      branches.main.name = "main";
      auth.access_token_path = config.sops.secrets."github_pat".path;
    }];
  };
}