{ pkgs, ... }: {
  environment.systemPackages = with pkgs; [
    git curl zsh fzf net-tools
  ];

  services.openssh.enable = true;
  users.defaultUserShell = pkgs.zsh;

  users.users.mafyuh = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    openssh.authorizedKeys.keys = [ "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC2I9wGjs+G/RO5aJJDNL0j5yPExvX7RETQIO6OmXbvx Generated By Termius" ];
  };
  security.sudo.wheelNeedsPassword = false;
}