{ pkgs, ... }: {
  programs.zsh.enable = true;
  users.defaultUserShell = pkgs.zsh;

  users.users.mafyuh = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [ "networkmanager" "wheel" "docker" ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC2I9wGjs+G/RO5aJJDNL0j5yPExvX7RETQIO6OmXbvx Generated By Termius"
    ];
  };

  security.sudo.wheelNeedsPassword = false;
}
